// INCLUDE FILE generated by "Pelles C for Windows, version 8.00".

#define IDS_FILEFILTER  10001
#define IDR_ICON1  8001

#define NELEMS(a)  (sizeof(a) / sizeof((a)[0]))

PWSTR DumpTypeLib(PCWSTR pszFilename);
#define IDS_MENUTEXT  10002
